version: "3.9"

services:
  filestore:
    image: cs348-filestore:latest
    ports:
      - 3001:3001
    volumes:
      - filestore:/files

  setup:
    image: cs348-setup:latest
    depends_on:
      - db
    links:
      - db
    environment:
      - DB_HOST=db

  webapp:
    image: cs348-music-app:latest
    depends_on:
      - db
    links:
      - db
      - filestore
    ports:
      - 3000:3000
    environment:
      - DB_HOST=db
      - FILESTORE_HOST=filestore

  db:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: musicapp

volumes:
  postgres:
  filestore: