version: "3.9"

services:
  webapp:
    image: music-app:latest
    depends_on:
      - db
    links:
      - db
    ports:
      - 3000:3000

  db:
    image: mariadb:latest
    restart: always
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: change-me
      MARIADB_DATABASE: "musicapp"

volumes:
  mariadb: