name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-filestore:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run:
        cd filestore
        docker build . --tag cs348-filestore:$(date +%s)
  
  build-setup:
  
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Build the docker image
      run: 
        cd setup
        docker build . --tag cs348-setup:$(date +%s)    

  build-music-app:
  
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Build the docker image
      run: 
        cd website
        docker build . --tag cs348-music-app:$(date +%s)
